In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2018'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to June
df3 = pd.read_html(url, header=0)[4] # Getting movies from July to September
df4 = pd.read_html(url, header=0)[5] # Getting movies from October to November

In [3]:
df1.head()

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.
0,J A N U A R Y,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2]
1,J A N U A R Y,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3]
2,J A N U A R Y,5,Stratton,Momentum Pictures / GFM Films,"Simon West (director); Duncan Falconer, Warren...",[4]
3,J A N U A R Y,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5]
4,J A N U A R Y,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6]

In [4]:
df2.head()

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,A P R I L,6,A Quiet Place,Paramount Pictures / Platinum Dunes / Sunday N...,John Krasinski (director/screenplay); Scott Be...,[76]
1,A P R I L,6,Blockers,Universal Pictures / Good Universe / Point Gre...,"Kay Cannon (director); Eben Russell, Jon Hurwi...",[77]
2,A P R I L,6,You Were Never Really Here,Amazon Studios,Lynne Ramsay (director/screenplay); Joaquin Ph...,[78]
3,A P R I L,6,Chappaquiddick,Entertainment Studios,"John Curran (director); Taylor Allen, Andrew L...",[79]
4,A P R I L,6,Pandas,Warner Bros. Pictures / IMAX,"Drew Fellman, David Douglas (directors); Drew ...",[80]

In [5]:
df3.head()

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J U L Y,4,The First Purge,Universal Pictures / Blumhouse Productions / P...,Gerard McMurray (director); James DeMonaco (sc...,[135]
1,J U L Y,6,Ant-Man and the Wasp,Marvel Studios / Walt Disney Studios Motion Pi...,"Peyton Reed (director); Chris McKenna, Erik So...",[136]
2,J U L Y,6,Sorry to Bother You,Annapurna Pictures,Boots Riley (director/screenplay); Lakeith Sta...,[137]
3,J U L Y,6,Whitney,Roadside Attractions / Miramax,Kevin MacDonald (director/screenplay); Whitney...,[138]
4,J U L Y,13,Hotel Transylvania 3: Summer Vacation,Columbia Pictures / Sony Pictures Animation / MRC,Genndy Tartakovsky (director/screenplay); Mich...,[139]

In [6]:
df4.head()

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,O C T O B E R,2,Power of the Air,Five & Two Pictures,Dave Christiano (director/screenplay); Nichola...,[204]
1,O C T O B E R,5,Venom,Columbia Pictures / Marvel Entertainment,"Ruben Fleischer (director); Jeff Pinkner, Scot...",[205]
2,O C T O B E R,5,A Star Is Born,Warner Bros. Pictures,Bradley Cooper (director/screenplay); Eric Rot...,[206]
3,O C T O B E R,5,The Great Buster: A Celebration,Cohen Media Group,Peter Bogdanovich (director),[207]
4,O C T O B E R,10,The Happy Prince,Sony Pictures Classics,Rupert Everett (director/screenplay); Rupert E...,[208]

In [7]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [8]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '5b310fa0acdaef472ceb07304163f191'

In [9]:
from tmdbv3api import Movie

tmdb_movie = Movie()
def get_genre(x): #pass in the title of the movies
    genres = []
    result = tmdb_movie.search(x) #the title will be searched in the tmdb_movie
    movie_id = result[0].id #we will match the "id" with the "title"
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key)) #we will get the result from the IMDb data
    data_json = response.json() # convert it to a json file
    if data_json['genres']: # only extract the "genre"
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name']) # add the "genre" to the empty genre list
        return genre_str.join(genres)
    else:
        np.NaN

In [11]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [12]:
df.head()

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,J A N U A R Y,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN,Horror Mystery Thriller
1,J A N U A R Y,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN,Thriller Drama
2,J A N U A R Y,5,Stratton,Momentum Pictures / GFM Films,"Simon West (director); Duncan Falconer, Warren...",[4],NaN,Action Thriller
3,J A N U A R Y,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN,Western Crime Thriller Drama
4,J A N U A R Y,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN,Action Thriller Mystery

In [13]:
df_2018 = df[['Title', 'Cast and crew', 'genres']]

In [14]:
df_2018

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery
...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie

In [15]:
df_2018['Cast and crew'][1]

'Lauren Wolkstein (director); Christopher Radcliff (co-director/screenplay); Alex Pettyfer, James Freedson-Jackson, Emily Althaus, Gene Jones, Owen Campbell, Tobias Campbell'

Here cast and crew are mixed. So, need to extract both separetely.

In [16]:
# Extract Directors
def get_directors(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [17]:
df_2018['director_name'] = df_2018['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\2468683354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['director_name'] = df_2018['Cast and crew'].apply(lambda x: get_directors(x))

In [18]:
df_2018

,Title,Cast and crew,genres,director_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra
...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade

In [19]:
# Extract Actor 1
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [20]:
df_2018['actor_1_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor1(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\292743101.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_1_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor1(x))

In [21]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [22]:
df_2018['actor_2_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor2(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\674470752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_2_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor2(x))

In [23]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [24]:
df_2018['actor_3_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor3(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1060695049.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_3_name'] = df_2018['Cast and crew'].apply(lambda x: get_actor3(x))

In [25]:
df_2018

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay,Christian Bale,Amy Adams,Steve Carell
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [26]:
df_2018 = df_2018.rename(columns={'Title': 'movie_title'})

In [27]:
df_2018

,movie_title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay,Christian Bale,Amy Adams,Steve Carell
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [28]:
ndf = df_2018.drop('Cast and crew', axis=1)

In [29]:
ndf.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,Western Crime Thriller Drama,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson

In [30]:
ndf['actor_2_name'] = ndf['actor_2_name'].replace(np.nan, 'unknown')
ndf['actor_3_name'] = ndf['actor_3_name'].replace(np.nan, 'unknown')

In [31]:
ndf['all'] = ndf['actor_1_name'] + " " + ndf['actor_2_name'] + " " + ndf['actor_3_name'] + " " + ndf['director_name'] + " " + ndf['genres']

In [32]:
ndf['all'][1]

'Alex Pettyfer James Freedson-Jackson Emily Althaus Lauren Wolkstein Thriller Drama'

In [33]:
df_2017 = pd.read_csv('newData.csv')

In [34]:
data_2018 = pd.concat([df_2017, ndf])

In [35]:
data_2018

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
270,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,Holmes & Watson,Will Ferrell John C. Reilly Rebecca Hall Etan ...
271,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,Vice,Christian Bale Amy Adams Steve Carell Adam McK...
272,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,On the Basis of Sex,Felicity Jones Armie Hammer Justin Theroux Mim...
273,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,Destroyer,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
274,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,Black Mirror: Bandersnatch,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

# Extracting 2019 data

In [36]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2019'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to June
df3 = pd.read_html(url, header=0)[4] # Getting movies from July to September
df4 = pd.read_html(url, header=0)[5] # Getting movies from October to November

In [37]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [38]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [39]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genres
0,J A N U A R Y,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2],Horror Thriller Mystery
1,J A N U A R Y,4,Rust Creek,IFC Films / Lunacy Productions,Jen McGowan (director); Julie Lipson (screenpl...,[3],Thriller Drama Action Crime
2,J A N U A R Y,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4],Thriller
3,J A N U A R Y,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5],Drama Adventure Family
4,J A N U A R Y,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6],Comedy Drama
...,...,...,...,...,...,...,...
240,D E C E M B E R,25,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132],Animation Action Adventure Comedy Family
241,D E C E M B E R,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[224],Drama Romance History
242,D E C E M B E R,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[225],War Drama History
243,D E C E M B E R,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[226],Drama Crime History
244,D E C E M B E R,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[227],Drama

In [40]:
df_2019 = df[['Title', 'Cast and crew', 'genres']]

In [41]:
df_2019['director_name'] = df_2019['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\15504405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['director_name'] = df_2019['Cast and crew'].apply(lambda x: get_directors(x))

In [42]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].apply(lambda x: get_actor1(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\207659982.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_1_name'] = df_2019['Cast and crew'].apply(lambda x: get_actor1(x))

In [43]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].apply(lambda x: get_actor2(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\2185615291.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_2_name'] = df_2019['Cast and crew'].apply(lambda x: get_actor2(x))

In [44]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].apply(lambda x: get_actor3(x))

In [45]:
df_2019.head()

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Horror Thriller Mystery,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama Action Crime,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman

In [46]:
df_2019.drop('Cast and crew', axis=1, inplace=True)

In [47]:
df_2019.columns

Index(['Title', 'genres', 'director_name', 'actor_1_name', 'actor_2_name',
       'actor_3_name'],
      dtype='object')

In [48]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [49]:
df_2019['actor_2_name'] = df_2019['actor_2_name'].replace(np.nan, 'unknown')
df_2019['actor_3_name'] = df_2019['actor_3_name'].replace(np.nan, 'unknown')

In [50]:
df_2019.isnull().sum()

movie_title      0
genres           0
director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
dtype: int64

In [51]:
df_2019['all'] = df_2019['actor_1_name'] + " " + df_2019['actor_2_name'] + " " + df_2019['actor_3_name'] + " " + df_2019['director_name'] + " " + df_2019['genres']

In [52]:
df_2019

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,all
0,Escape Room,Horror Thriller Mystery,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Rust Creek,Thriller Drama Action Crime,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,American Hangman,Thriller,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Donald Sutherland Vincent Kartheiser Oliver De...
3,A Dog's Way Home,Drama Adventure Family,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Bryce Dallas Howard Edward James Olmos Alexand...
4,The Upside,Comedy Drama,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
240,Spies in Disguise,Animation Action Adventure Comedy Family,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Will Smith Tom Holland Rashida Jones Nick Brun...
241,Little Women,Drama Romance History,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Saoirse Ronan Emma Watson Florence Pugh Greta ...
242,1917,War Drama History,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,George MacKay Dean-Charles Chapman Mark Strong...
243,Just Mercy,Drama Crime History,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Michael B. Jordan Jamie Foxx Brie Larson Desti...
244,Clemency,Drama,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [53]:
data_2019 = pd.concat([data_2018, df_2019])

In [54]:
data_2019

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
240,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,Spies in Disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
241,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance History,Little Women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
242,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama History,1917,George MacKay Dean-Charles Chapman Mark Strong...
243,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,Just Mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
244,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,Clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

# Extracting 2020 data

In [55]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2020'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to June
df3 = pd.read_html(url, header=0)[4] # Getting movies from July to September
df4 = pd.read_html(url, header=0)[5] # Getting movies from October to November

In [56]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [57]:
def get_genres(x):
    genres = []
    result = tmdb_movie.search(x)
    if result:  # Check if the result list is not empty
        movie_id = result[0].id
        response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
        data_json = response.json()
        if data_json['genres']:
            genres = [genre['name'] for genre in data_json['genres']]
    return genres

In [58]:
df['genres'] = df['Title'].map(lambda x: get_genres(str(x)))

In [59]:
df_2020 = df[['Title', 'Cast and crew', 'genres']]

In [60]:
df_2020['director_name'] = df_2020['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\2549193815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['director_name'] = df_2020['Cast and crew'].apply(lambda x: get_directors(x))

In [61]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor1(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\414567563.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_1_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor1(x))

In [62]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor2(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1417751948.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_2_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor2(x))

In [63]:
df_2020['actor_3_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor3(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1656537317.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_3_name'] = df_2020['Cast and crew'].apply(lambda x: get_actor3(x))

In [64]:
df_2020

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,"[Horror, Mystery]",Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho
1,Underwater,"William Eubank (director); Brian Duffield, Ada...","[Horror, Science Fiction, Action, Adventure]",William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",[Comedy],Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,[Drama],Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,"[Crime, Thriller, Drama]",Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs
...,...,...,...,...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,"[Family, Action, Fantasy, Comedy]",Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,"[Drama, Western, Adventure, Action]",Paul Greengrass,Tom Hanks,Helena Zengel,NaN
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,[Drama],Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,"[Thriller, Crime, Drama]",Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie
274,Pieces of a Woman,Kornél Mundruczó (director); Kata Wéber (scree...,[Drama],Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker

In [65]:
df_2020.drop('Cast and crew', axis=1, inplace=True)

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1946414122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020.drop('Cast and crew', axis=1, inplace=True)

In [66]:
df_2020.columns

Index(['Title', 'genres', 'director_name', 'actor_1_name', 'actor_2_name',
       'actor_3_name'],
      dtype='object')

In [67]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [68]:
df_2020['actor_2_name'] = df_2020['actor_2_name'].replace(np.nan, 'unknown')
df_2020['actor_3_name'] = df_2020['actor_3_name'].replace(np.nan, 'unknown')

In [69]:
df_2020['genres'] = df_2020['genres'].apply(lambda x: ' '.join(x))

In [70]:
df_2020['all'] = df_2020['actor_1_name'] + " " + df_2020['actor_2_name'] + " " + df_2020['actor_3_name'] + " " + df_2020['director_name'] + " " + df_2020['genres']

In [71]:
df_2020

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,all
0,The Grudge,Horror Mystery,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho,Andrea Riseborough Demián Bichir John Cho Nico...
1,Underwater,Horror Science Fiction Action Adventure,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Like a Boss,Comedy,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Three Christs,Drama,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Inherit the Viper,Crime Thriller Drama,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
270,We Can Be Heroes,Family Action Fantasy Comedy,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
271,News of the World,Drama Western Adventure Action,Paul Greengrass,Tom Hanks,Helena Zengel,unknown,Tom Hanks Helena Zengel unknown Paul Greengras...
272,One Night in Miami...,Drama,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
273,Promising Young Woman,Thriller Crime Drama,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Carey Mulligan Bo Burnham Alison Brie Emerald ...
274,Pieces of a Woman,Drama,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

In [72]:
data_2020 = pd.concat([data_2019, df_2020])

In [73]:
data_2020

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Family Action Fantasy Comedy,We Can Be Heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
271,Paul Greengrass,Tom Hanks,Helena Zengel,unknown,Drama Western Adventure Action,News of the World,Tom Hanks Helena Zengel unknown Paul Greengras...
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,Promising Young Woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
274,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,Pieces of a Woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

# Extracting 2021 data

In [74]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2021'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to June
df3 = pd.read_html(url, header=0)[4] # Getting movies from July to September
df4 = pd.read_html(url, header=0)[5] # Getting movies from October to November

In [75]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [86]:
df['genres'] = df['Title'].map(lambda x: get_genres(str(x)))

In [87]:
df['genres'] = df['genres'].apply(lambda x: ' '.join(x))

In [88]:
df_2021 = df[['Title', 'Cast and crew', 'genres']]

In [89]:
df_2021

,Title,Cast and crew,genres
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History
4,Outside the Wire,"Mikael Håfström (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction
...,...,...,...
356,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War
357,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance
358,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama
359,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama
360,NaN,NaN,Drama

In [94]:
df_2021['director_name'] = df_2021['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\925798734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['director_name'] = df_2021['Cast and crew'].apply(lambda x: get_directors(x))

In [95]:
df_2021['actor_1_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor1(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\737843542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_1_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor1(x))

In [96]:
df_2021['actor_2_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor2(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\4093058140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_2_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor2(x))

In [97]:
df_2021['actor_3_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor3(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1232270555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_3_name'] = df_2021['Cast and crew'].apply(lambda x: get_actor3(x))

In [98]:
df_2021.drop('Cast and crew', axis=1, inplace=True)

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\3711573756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021.drop('Cast and crew', axis=1, inplace=True)

In [99]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [100]:
df_2021['actor_2_name'] = df_2021['actor_2_name'].replace(np.nan, 'unknown')
df_2021['actor_3_name'] = df_2021['actor_3_name'].replace(np.nan, 'unknown')

In [101]:
df_2021['all'] = df_2021['actor_1_name'] + " " + df_2021['actor_2_name'] + " " + df_2021['actor_3_name'] + " " + df_2021['director_name'] + " " + df_2021['genres']

In [102]:
df_2021.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,all
0,Shadow in the Cloud,Horror Action War,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Beulah Koale,Chloë Grace Moretz Taylor John Smith Beulah Ko...
1,The White Tiger,Drama,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Adarsh Gourav Rajkummar Rao Priyanka Chopra Jo...
2,Locked Down,Comedy Crime Drama,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Anne Hathaway Chiwetel Ejiofor Stephen Merchan...
3,The Dig,Drama History,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Carey Mulligan Ralph Fiennes Lily James Simon ...
4,Outside the Wire,Thriller Action Science Fiction,Mikael Håfström,Anthony Mackie,Damson Idris,Emily Beecham,Anthony Mackie Damson Idris Emily Beecham Mika...

In [103]:
data_2021 = pd.concat([data_2020, df_2021])

In [104]:
data_2021

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,The Tragedy of Macbeth,Denzel Washington Frances McDormand Bertie Car...
357,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian,Drama Romance,A Journal for Jordan,Michael B. Jordan Chanté Adams Jalon Christian...
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,American Underdog,Zachary Levi Anna Paquin Dennis Quaid Erwin br...
359,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin Díaz,Jeanne Balibar,Drama,Memoria,Apichatpong Weerasethakul (director/acreenplay...
360,nan,nan,unknown,unknown,Drama,NaN,nan unknown unknown nan Drama

In [105]:
data_2021.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      1
all              0
dtype: int64

In [106]:
data_2021.dropna(inplace=True, how='any')

# Extracting 2022 data

In [108]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2022'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to June
df3 = pd.read_html(url, header=0)[4] # Getting movies from July to September
df4 = pd.read_html(url, header=0)[5] # Getting movies from October to November

In [109]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [112]:
df['genres'] = df['Title'].map(lambda x: get_genres(str(x)))

In [113]:
df['genres'] = df['genres'].apply(lambda x: ' '.join(x))

In [114]:
df_2022 = df[['Title', 'Cast and crew', 'genres']]

In [117]:
df_2022['director_name'] = df_2022['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1621507339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['director_name'] = df_2022['Cast and crew'].apply(lambda x: get_directors(x))

In [118]:
df_2022['actor_1_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor1(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\723271481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_1_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor1(x))

In [119]:
df_2022['actor_2_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor2(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1924677473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_2_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor2(x))

In [120]:
df_2022['actor_3_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor3(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1552884725.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_3_name'] = df_2022['Cast and crew'].apply(lambda x: get_actor3(x))

In [121]:
df_2022.drop('Cast and crew', axis=1, inplace=True)

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\921750998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022.drop('Cast and crew', axis=1, inplace=True)

In [122]:
df_2022 = df_2022.rename(columns={'Title':'movie_title'})

In [127]:
df_2022

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,all
0,The 355,Action Thriller,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,Penélope Cruz,Jessica Chastain Lupita Nyong'o Penélope Cruz ...
1,The Legend of La Llorona,Family Animation Fantasy Horror,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo,Autumn Reeser Antonio Cupo Danny Trejo Patrici...
2,The Commando,Action Crime Thriller,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Mickey Rourke Michael Jai White unknown Asif A...
3,American Siege,Action Adventure Thriller,Edward Drake,Timothy V. Murphy,Bruce Willis,unknown,Timothy V. Murphy Bruce Willis unknown Edward ...
4,Scream,Horror Mystery Thriller,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
324,"Alice, Darling",Thriller Mystery Drama,Mary Nighy,Anna Kendrick,Kaniehtiio Horn,Charlie Carrick,Anna Kendrick Kaniehtiio Horn Charlie Carrick ...
325,NaN,Drama,nan,nan,unknown,unknown,nan unknown unknown nan Drama
326,NaN,Drama,nan,nan,unknown,unknown,nan unknown unknown nan Drama
327,NaN,Drama,nan,nan,unknown,unknown,nan unknown unknown nan Drama
328,NaN,Drama,nan,nan,unknown,unknown,nan unknown unknown nan Drama

In [123]:
df_2022['actor_2_name'] = df_2022['actor_2_name'].replace(np.nan, 'unknown')
df_2022['actor_3_name'] = df_2022['actor_3_name'].replace(np.nan, 'unknown')

In [124]:
df_2022['all'] = df_2022['actor_1_name'] + " " + df_2022['actor_2_name'] + " " + df_2022['actor_3_name'] + " " + df_2022['director_name'] + " " + df_2022['genres']

In [125]:
data_2022 = pd.concat([data_2021, df_2022])

In [129]:
data_2022.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      4
all              0
dtype: int64

In [131]:
data_2022.dropna(inplace=True, how='any')

In [133]:
data_2022

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
320,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,Whitney Houston: I Wanna Dance with Somebody,Naomi Ackie Stanley Tucci Ashton Sanders Kasi ...
321,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Crime,The Pale Blue Eye,Christian Bale Harry Melling Gillian Anderson ...
322,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama,Women Talking,Rooney Mara Claire Foy Jessie Buckley Sarah Po...
323,Marc Forster,Tom Hanks,Mariana Treviño,Rachel Keller,Comedy Drama,A Man Called Otto,Tom Hanks Mariana Treviño Rachel Keller Marc F...
324,Mary Nighy,Anna Kendrick,Kaniehtiio Horn,Charlie Carrick,Thriller Mystery Drama,"Alice, Darling",Anna Kendrick Kaniehtiio Horn Charlie Carrick ...

# Extracting 2023 Data

In [139]:
url = 'https://en.wikipedia.org/wiki/List_of_American_films_of_2023'
df1 = pd.read_html(url, header=0)[2] # Getting movies from Januray to March
df2 = pd.read_html(url, header=0)[3] # Getting movies from April to May

In [140]:
df = pd.concat([df1, df2], ignore_index=True)

In [143]:
df['genres'] = df['Title'].map(lambda x: get_genres(str(x)))

In [144]:
df['Cast and crew'] = df['Cast and crew'].astype(str)

In [145]:
df['genres'] = df['genres'].apply(lambda x: ' '.join(x))

In [146]:
df_2023 = df[['Title', 'Cast and crew', 'genres']]

In [147]:
df_2023['director_name'] = df_2023['Cast and crew'].apply(lambda x: get_directors(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\4127589974.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['director_name'] = df_2023['Cast and crew'].apply(lambda x: get_directors(x))

In [148]:
df_2023['actor_1_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor1(x))
df_2023['actor_2_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor2(x))
df_2023['actor_3_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor3(x))

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\3361584494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_1_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor1(x))
C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\3361584494.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_2_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor2(x))
C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\3361584494.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_3_name'] = df_2023['Cast and crew'].apply(lambda x: get_actor3(x))

In [149]:
df_2023.drop('Cast and crew', axis=1, inplace=True)

C:\Users\amanr\AppData\Local\Temp\ipykernel_23188\1109304816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.drop('Cast and crew', axis=1, inplace=True)

In [150]:
df_2023 = df_2023.rename(columns={'Title':'movie_title'})

In [151]:
df_2023

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Super Mario Bros. Movie*,Animation Family Adventure Fantasy Comedy,nan,nan,NaN,NaN
1,Guardians of the Galaxy Vol. 3*,Science Fiction Adventure Action,nan,nan,NaN,NaN
2,Ant-Man and the Wasp: Quantumania*,Action Adventure Science Fiction,nan,nan,NaN,NaN
3,The Little Mermaid*,Adventure Family Fantasy Romance,nan,nan,NaN,NaN
4,John Wick: Chapter 4*,Action Thriller Crime,nan,nan,NaN,NaN
...,...,...,...,...,...,...
75,Space Oddity,Comedy Romance Science Fiction,Kyra Sedgwick,Kyle Allen,Alexandra Shipp,Madeline Brewer
76,A Thousand and One,Drama,A.V. Rockwell,Teyana Taylor,Will Catlett,Josiah Cross
77,Assassin,Action Science Fiction,Jesse Atlas,Nomzamo Mbatha,Dominic Purcell,Bruce Willis
78,Acidman,Drama,Alex Lehmann,Thomas Haden Church,Dianna Agron,NaN
79,Malum,Horror,Anthony DiBlasi,Jessica Sula,Candice Coke,Chaney Morrow

In [152]:
df_2023['actor_2_name'] = df_2023['actor_2_name'].replace(np.nan, 'unknown')
df_2023['actor_3_name'] = df_2023['actor_3_name'].replace(np.nan, 'unknown')

In [153]:
df_2023['all'] = df_2023['actor_1_name'] + " " + df_2023['actor_2_name'] + " " + df_2023['actor_3_name'] + " " + df_2023['director_name'] + " " + df_2023['genres']

In [154]:
data_2023 = pd.concat([data_2022, df_2023])

In [155]:
data_2023

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,all
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,Avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,The Dark Knight Rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Star Wars: Episode VII - The Force Awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
75,Kyra Sedgwick,Kyle Allen,Alexandra Shipp,Madeline Brewer,Comedy Romance Science Fiction,Space Oddity,Kyle Allen Alexandra Shipp Madeline Brewer Kyr...
76,A.V. Rockwell,Teyana Taylor,Will Catlett,Josiah Cross,Drama,A Thousand and One,Teyana Taylor Will Catlett Josiah Cross A.V. R...
77,Jesse Atlas,Nomzamo Mbatha,Dominic Purcell,Bruce Willis,Action Science Fiction,Assassin,Nomzamo Mbatha Dominic Purcell Bruce Willis Je...
78,Alex Lehmann,Thomas Haden Church,Dianna Agron,unknown,Drama,Acidman,Thomas Haden Church Dianna Agron unknown Alex ...
79,Anthony DiBlasi,Jessica Sula,Candice Coke,Chaney Morrow,Horror,Malum,Jessica Sula Candice Coke Chaney Morrow Anthon...

In [157]:
data_2023.to_csv('final_df.csv', index=False)